/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './modules/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      currentColor: 'current',
      inherit: 'inherit',
      black: 'black',
      white: 'white',

      background: 'var(--color-white)',
      'background-alt': 'var(--color-gray2)',
      brand: 'var(--color-brand)',
      primary: 'var(--color-blue10)',
      secondary: 'var(--color-slate11)',
      support: 'var(--color-gray11)',
      dark: 'var(--color-slate2Dark)',
      body: 'var(--color-slate12)',
      error: 'var(--color-red11)',

      link: {
        DEFAULT: 'var(--color-blue11)',
        hover: 'var(--color-blue12)',
      },

      layer: {
        DEFAULT: 'var(--color-gray3)',
        alt: 'var(--color-white)',
        hover: 'var(--color-gray4)',
        active: 'var(--color-gray5)',
      },

      field: {
        DEFAULT: 'white',
        alt: 'var(--color-slate2)',
        hover: 'var(--color-slate4)',
      },

      border: {
        interactive: 'var(--color-blue10)',
        subtle: {
          DEFAULT: 'var(--color-slate2)',
          dark: 'var(--color-slate3)',
          darker: 'var(--color-slate6)',
        },
        strong: {
          DEFAULT: 'var(--color-slate7)',
          dark: 'var(--color-slate8)',
          darker: 'var(--color-slate9)',
          darkest: 'var(--color-slate11)',
        },
      },

      focus: {
        DEFAULT: 'var(--color-blue9)',
        inset: 'var(--color-white)',
      },

      icon: {
        DEFAULT: 'var(--color-slate12)',
        white: 'white',
        neg: 'var(--color-red10)',
        pos: 'var(--color-green10)',
        warn: 'var(--color-yellow8)',
        info: 'var(--color-blue10)',
        dark: 'var(--color-slate12)',
      },

      overlay: {
        DEFAULT: 'var(--color-black10)',
        neg: 'var(--color-mauve12)',
      },

      neg: {
        DEFAULT: 'var(--color-red10)',
        bg: 'var(--color-red4)',
        overlay: 'var(--color-mauve12)',
        dark: 'var(--color-red12)',
        border: 'var(--color-red10)',
        icon: 'var(--color-red10)',
        text: 'var(--color-red11)',
        hover: 'var(--color-red11)',
        active: 'var(--color-red11)',
        focus: 'var(--color-red7)',
      },

      pos: {
        DEFAULT: 'var(--color-green11)',
        bg: 'var(--color-green4)',
        dark: 'var(--color-green12)',
        border: 'var(--color-green10)',
        icon: 'var(--color-green10)',
        text: 'var(--color-green11)',
        hover: 'var(--color-green5)',
        active: 'var(--color-green6)',
        focus: 'var(--color-green7)',
      },

      warn: {
        bg: 'var(--color-yellow3)',
        base: 'var(--color-yellow8)',
        dark: 'var(--color-yellow12)',
        border: 'var(--color-yellow8)',
        icon: 'var(--color-yellow8)',
        text: 'var(--color-yellow11)',
        hover: 'var(--color-yellow5)',
        active: 'var(--color-yellow6)',
        focus: 'var(--color-yellow7)',
      },

      info: {
        bg: 'var(--color-blue4)',
        base: 'var(--color-blue10)',
        dark: 'var(--color-blue12)',
        border: 'var(--color-blue10)',
        icon: 'var(--color-blue10)',
        text: 'var(--color-blue11)',
        hover: 'var(--color-blue5)',
        active: 'var(--color-blue6)',
        focus: 'var(--color-blue7)',
      },

      gray1: 'var(--color-gray1)',
      gray2: 'var(--color-gray2)',
      gray3: 'var(--color-gray3)',
      gray4: 'var(--color-gray4)',
      gray5: 'var(--color-gray5)',
      gray6: 'var(--color-gray6)',
      gray7: 'var(--color-gray7)',
      gray8: 'var(--color-gray8)',
      gray9: 'var(--color-gray9)',
      gray10: 'var(--color-gray10)',
      gray11: 'var(--color-gray11)',
      gray12: 'var(--color-gray12)',

      mauve1: 'var(--color-mauve1)',
      mauve2: 'var(--color-mauve2)',
      mauve3: 'var(--color-mauve3)',
      mauve4: 'var(--color-mauve4)',
      mauve5: 'var(--color-mauve5)',
      mauve6: 'var(--color-mauve6)',
      mauve7: 'var(--color-mauve7)',
      mauve8: 'var(--color-mauve8)',
      mauve9: 'var(--color-mauve9)',
      mauve10: 'var(--color-mauve10)',
      mauve11: 'var(--color-mauve11)',
      mauve12: 'var(--color-mauve12)',

      slate1: 'var(--color-slate1)',
      slate2: 'var(--color-slate2)',
      slate3: 'var(--color-slate3)',
      slate4: 'var(--color-slate4)',
      slate5: 'var(--color-slate5)',
      slate6: 'var(--color-slate6)',
      slate7: 'var(--color-slate7)',
      slate8: 'var(--color-slate8)',
      slate9: 'var(--color-slate9)',
      slate10: 'var(--color-slate10)',
      slate11: 'var(--color-slate11)',
      slate12: 'var(--color-slate12)',

      sage1: 'var(--color-sage1)',
      sage2: 'var(--color-sage2)',
      sage3: 'var(--color-sage3)',
      sage4: 'var(--color-sage4)',
      sage5: 'var(--color-sage5)',
      sage6: 'var(--color-sage6)',
      sage7: 'var(--color-sage7)',
      sage8: 'var(--color-sage8)',
      sage9: 'var(--color-sage9)',
      sage10: 'var(--color-sage10)',
      sage11: 'var(--color-sage11)',
      sage12: 'var(--color-sage12)',

      olive1: 'var(--color-olive1)',
      olive2: 'var(--color-olive2)',
      olive3: 'var(--color-olive3)',
      olive4: 'var(--color-olive4)',
      olive5: 'var(--color-olive5)',
      olive6: 'var(--color-olive6)',
      olive7: 'var(--color-olive7)',
      olive8: 'var(--color-olive8)',
      olive9: 'var(--color-olive9)',
      olive10: 'var(--color-olive10)',
      olive11: 'var(--color-olive11)',
      olive12: 'var(--color-olive12)',

      sand1: 'var(--color-sand1)',
      sand2: 'var(--color-sand2)',
      sand3: 'var(--color-sand3)',
      sand4: 'var(--color-sand4)',
      sand5: 'var(--color-sand5)',
      sand6: 'var(--color-sand6)',
      sand7: 'var(--color-sand7)',
      sand8: 'var(--color-sand8)',
      sand9: 'var(--color-sand9)',
      sand10: 'var(--color-sand10)',
      sand11: 'var(--color-sand11)',
      sand12: 'var(--color-sand12)',

      tomato1: 'var(--color-tomato1)',
      tomato2: 'var(--color-tomato2)',
      tomato3: 'var(--color-tomato3)',
      tomato4: 'var(--color-tomato4)',
      tomato5: 'var(--color-tomato5)',
      tomato6: 'var(--color-tomato6)',
      tomato7: 'var(--color-tomato7)',
      tomato8: 'var(--color-tomato8)',
      tomato9: 'var(--color-tomato9)',
      tomato10: 'var(--color-tomato10)',
      tomato11: 'var(--color-tomato11)',
      tomato12: 'var(--color-tomato12)',

      red1: 'var(--color-red1)',
      red2: 'var(--color-red2)',
      red3: 'var(--color-red3)',
      red4: 'var(--color-red4)',
      red5: 'var(--color-red5)',
      red6: 'var(--color-red6)',
      red7: 'var(--color-red7)',
      red8: 'var(--color-red8)',
      red9: 'var(--color-red9)',
      red10: 'var(--color-red10)',
      red11: 'var(--color-red11)',
      red12: 'var(--color-red12)',

      crimson1: 'var(--color-crimson1)',
      crimson2: 'var(--color-crimson2)',
      crimson3: 'var(--color-crimson3)',
      crimson4: 'var(--color-crimson4)',
      crimson5: 'var(--color-crimson5)',
      crimson6: 'var(--color-crimson6)',
      crimson7: 'var(--color-crimson7)',
      crimson8: 'var(--color-crimson8)',
      crimson9: 'var(--color-crimson9)',
      crimson10: 'var(--color-crimson10)',
      crimson11: 'var(--color-crimson11)',
      crimson12: 'var(--color-crimson12)',

      pink1: 'var(--color-pink1)',
      pink2: 'var(--color-pink2)',
      pink3: 'var(--color-pink3)',
      pink4: 'var(--color-pink4)',
      pink5: 'var(--color-pink5)',
      pink6: 'var(--color-pink6)',
      pink7: 'var(--color-pink7)',
      pink8: 'var(--color-pink8)',
      pink9: 'var(--color-pink9)',
      pink10: 'var(--color-pink10)',
      pink11: 'var(--color-pink11)',
      pink12: 'var(--color-pink12)',

      plum1: 'var(--color-plum1)',
      plum2: 'var(--color-plum2)',
      plum3: 'var(--color-plum3)',
      plum4: 'var(--color-plum4)',
      plum5: 'var(--color-plum5)',
      plum6: 'var(--color-plum6)',
      plum7: 'var(--color-plum7)',
      plum8: 'var(--color-plum8)',
      plum9: 'var(--color-plum9)',
      plum10: 'var(--color-plum10)',
      plum11: 'var(--color-plum11)',
      plum12: 'var(--color-plum12)',

      purple1: 'var(--color-purple1)',
      purple2: 'var(--color-purple2)',
      purple3: 'var(--color-purple3)',
      purple4: 'var(--color-purple4)',
      purple5: 'var(--color-purple5)',
      purple6: 'var(--color-purple6)',
      purple7: 'var(--color-purple7)',
      purple8: 'var(--color-purple8)',
      purple9: 'var(--color-purple9)',
      purple10: 'var(--color-purple10)',
      purple11: 'var(--color-purple11)',
      purple12: 'var(--color-purple12)',

      violet1: 'var(--color-violet1)',
      violet2: 'var(--color-violet2)',
      violet3: 'var(--color-violet3)',
      violet4: 'var(--color-violet4)',
      violet5: 'var(--color-violet5)',
      violet6: 'var(--color-violet6)',
      violet7: 'var(--color-violet7)',
      violet8: 'var(--color-violet8)',
      violet9: 'var(--color-violet9)',
      violet10: 'var(--color-violet10)',
      violet11: 'var(--color-violet11)',
      violet12: 'var(--color-violet12)',

      indigo1: 'var(--color-indigo1)',
      indigo2: 'var(--color-indigo2)',
      indigo3: 'var(--color-indigo3)',
      indigo4: 'var(--color-indigo4)',
      indigo5: 'var(--color-indigo5)',
      indigo6: 'var(--color-indigo6)',
      indigo7: 'var(--color-indigo7)',
      indigo8: 'var(--color-indigo8)',
      indigo9: 'var(--color-indigo9)',
      indigo10: 'var(--color-indigo10)',
      indigo11: 'var(--color-indigo11)',
      indigo12: 'var(--color-indigo12)',

      blue1: 'var(--color-blue1)',
      blue2: 'var(--color-blue2)',
      blue3: 'var(--color-blue3)',
      blue4: 'var(--color-blue4)',
      blue5: 'var(--color-blue5)',
      blue6: 'var(--color-blue6)',
      blue7: 'var(--color-blue7)',
      blue8: 'var(--color-blue8)',
      blue9: 'var(--color-blue9)',
      blue10: 'var(--color-blue10)',
      blue11: 'var(--color-blue11)',
      blue12: 'var(--color-blue12)',

      sky1: 'var(--color-sky1)',
      sky2: 'var(--color-sky2)',
      sky3: 'var(--color-sky3)',
      sky4: 'var(--color-sky4)',
      sky5: 'var(--color-sky5)',
      sky6: 'var(--color-sky6)',
      sky7: 'var(--color-sky7)',
      sky8: 'var(--color-sky8)',
      sky9: 'var(--color-sky9)',
      sky10: 'var(--color-sky10)',
      sky11: 'var(--color-sky11)',
      sky12: 'var(--color-sky12)',

      mint1: 'var(--color-mint1)',
      mint2: 'var(--color-mint2)',
      mint3: 'var(--color-mint3)',
      mint4: 'var(--color-mint4)',
      mint5: 'var(--color-mint5)',
      mint6: 'var(--color-mint6)',
      mint7: 'var(--color-mint7)',
      mint8: 'var(--color-mint8)',
      mint9: 'var(--color-mint9)',
      mint10: 'var(--color-mint10)',
      mint11: 'var(--color-mint11)',
      mint12: 'var(--color-mint12)',

      cyan1: 'var(--color-cyan1)',
      cyan2: 'var(--color-cyan2)',
      cyan3: 'var(--color-cyan3)',
      cyan4: 'var(--color-cyan4)',
      cyan5: 'var(--color-cyan5)',
      cyan6: 'var(--color-cyan6)',
      cyan7: 'var(--color-cyan7)',
      cyan8: 'var(--color-cyan8)',
      cyan9: 'var(--color-cyan9)',
      cyan10: 'var(--color-cyan10)',
      cyan11: 'var(--color-cyan11)',
      cyan12: 'var(--color-cyan12)',

      teal1: 'var(--color-teal1)',
      teal2: 'var(--color-teal2)',
      teal3: 'var(--color-teal3)',
      teal4: 'var(--color-teal4)',
      teal5: 'var(--color-teal5)',
      teal6: 'var(--color-teal6)',
      teal7: 'var(--color-teal7)',
      teal8: 'var(--color-teal8)',
      teal9: 'var(--color-teal9)',
      teal10: 'var(--color-teal10)',
      teal11: 'var(--color-teal11)',
      teal12: 'var(--color-teal12)',

      green1: 'var(--color-green1)',
      green2: 'var(--color-green2)',
      green3: 'var(--color-green3)',
      green4: 'var(--color-green4)',
      green5: 'var(--color-green5)',
      green6: 'var(--color-green6)',
      green7: 'var(--color-green7)',
      green8: 'var(--color-green8)',
      green9: 'var(--color-green9)',
      green10: 'var(--color-green10)',
      green11: 'var(--color-green11)',
      green12: 'var(--color-green12)',

      grass1: 'var(--color-grass1)',
      grass2: 'var(--color-grass2)',
      grass3: 'var(--color-grass3)',
      grass4: 'var(--color-grass4)',
      grass5: 'var(--color-grass5)',
      grass6: 'var(--color-grass6)',
      grass7: 'var(--color-grass7)',
      grass8: 'var(--color-grass8)',
      grass9: 'var(--color-grass9)',
      grass10: 'var(--color-grass10)',
      grass11: 'var(--color-grass11)',
      grass12: 'var(--color-grass12)',

      lime1: 'var(--color-lime1)',
      lime2: 'var(--color-lime2)',
      lime3: 'var(--color-lime3)',
      lime4: 'var(--color-lime4)',
      lime5: 'var(--color-lime5)',
      lime6: 'var(--color-lime6)',
      lime7: 'var(--color-lime7)',
      lime8: 'var(--color-lime8)',
      lime9: 'var(--color-lime9)',
      lime10: 'var(--color-lime10)',
      lime11: 'var(--color-lime11)',
      lime12: 'var(--color-lime12)',

      yellow1: 'var(--color-yellow1)',
      yellow2: 'var(--color-yellow2)',
      yellow3: 'var(--color-yellow3)',
      yellow4: 'var(--color-yellow4)',
      yellow5: 'var(--color-yellow5)',
      yellow6: 'var(--color-yellow6)',
      yellow7: 'var(--color-yellow7)',
      yellow8: 'var(--color-yellow8)',
      yellow9: 'var(--color-yellow9)',
      yellow10: 'var(--color-yellow10)',
      yellow11: 'var(--color-yellow11)',
      yellow12: 'var(--color-yellow12)',

      amber1: 'var(--color-amber1)',
      amber2: 'var(--color-amber2)',
      amber3: 'var(--color-amber3)',
      amber4: 'var(--color-amber4)',
      amber5: 'var(--color-amber5)',
      amber6: 'var(--color-amber6)',
      amber7: 'var(--color-amber7)',
      amber8: 'var(--color-amber8)',
      amber9: 'var(--color-amber9)',
      amber10: 'var(--color-amber10)',
      amber11: 'var(--color-amber11)',
      amber12: 'var(--color-amber12)',

      orange1: 'var(--color-orange1)',
      orange2: 'var(--color-orange2)',
      orange3: 'var(--color-orange3)',
      orange4: 'var(--color-orange4)',
      orange5: 'var(--color-orange5)',
      orange6: 'var(--color-orange6)',
      orange7: 'var(--color-orange7)',
      orange8: 'var(--color-orange8)',
      orange9: 'var(--color-orange9)',
      orange10: 'var(--color-orange10)',
      orange11: 'var(--color-orange11)',
      orange12: 'var(--color-orange12)',

      brown1: 'var(--color-brown1)',
      brown2: 'var(--color-brown2)',
      brown3: 'var(--color-brown3)',
      brown4: 'var(--color-brown4)',
      brown5: 'var(--color-brown5)',
      brown6: 'var(--color-brown6)',
      brown7: 'var(--color-brown7)',
      brown8: 'var(--color-brown8)',
      brown9: 'var(--color-brown9)',
      brown10: 'var(--color-brown10)',
      brown11: 'var(--color-brown11)',
      brown12: 'var(--color-brown12)',

      bronze1: 'var(--color-bronze1)',
      bronze2: 'var(--color-bronze2)',
      bronze3: 'var(--color-bronze3)',
      bronze4: 'var(--color-bronze4)',
      bronze5: 'var(--color-bronze5)',
      bronze6: 'var(--color-bronze6)',
      bronze7: 'var(--color-bronze7)',
      bronze8: 'var(--color-bronze8)',
      bronze9: 'var(--color-bronze9)',
      bronze10: 'var(--color-bronze10)',
      bronze11: 'var(--color-bronze11)',
      bronze12: 'var(--color-bronze12)',

      gold1: 'var(--color-gold1)',
      gold2: 'var(--color-gold2)',
      gold3: 'var(--color-gold3)',
      gold4: 'var(--color-gold4)',
      gold5: 'var(--color-gold5)',
      gold6: 'var(--color-gold6)',
      gold7: 'var(--color-gold7)',
      gold8: 'var(--color-gold8)',
      gold9: 'var(--color-gold9)',
      gold10: 'var(--color-gold10)',
      gold11: 'var(--color-gold11)',
      gold12: 'var(--color-gold12)',

      gray1Dark: 'var(--color-gray1Dark)',
      gray2Dark: 'var(--color-gray2Dark)',
      gray3Dark: 'var(--color-gray3Dark)',
      gray4Dark: 'var(--color-gray4Dark)',
      gray5Dark: 'var(--color-gray5Dark)',
      gray6Dark: 'var(--color-gray6Dark)',
      gray7Dark: 'var(--color-gray7Dark)',
      gray8Dark: 'var(--color-gray8Dark)',
      gray9Dark: 'var(--color-gray9Dark)',
      gray10Dark: 'var(--color-gray10Dark)',
      gray11Dark: 'var(--color-gray11Dark)',
      gray12Dark: 'var(--color-gray12Dark)',

      slate1Dark: 'var(--color-slate1Dark)',
      slate2Dark: 'var(--color-slate2Dark)',
      slate3Dark: 'var(--color-slate3Dark)',
      slate4Dark: 'var(--color-slate4Dark)',
      slate5Dark: 'var(--color-slate5Dark)',
      slate6Dark: 'var(--color-slate6Dark)',
      slate7Dark: 'var(--color-slate7Dark)',
      slate8Dark: 'var(--color-slate8Dark)',
      slate9Dark: 'var(--color-slate9Dark)',
      slate10Dark: 'var(--color-slate10Dark)',
      slate11Dark: 'var(--color-slate11Dark)',
      slate12Dark: 'var(--color-slate12Dark)',
    },
    extend: {
      height: {
        header: '4rem',
      },
      width: {
        content: '1544px',
        'left-sidepanel': '376px',
      },
      minHeight: ({ theme }) => ({
        'screen-no-header': `calc(100vh - ${theme('height.header')})`,
      }),
      boxShadow: {
        custom:
          '1px -3px 3px -2px rgb(0 0 0 / 20%), 0 3px 3px -2px rgb(0 0 0 / 20%), 0 3px 4px 0 rgb(0 0 0 / 14%), 0 1px 8px 0 rgb(0 0 0 / 12%)',
        module:
          '0px 0px 29px rgba(0, 0, 0, 0.13), 0px 0px 44px rgba(0, 0, 0, 0.15), 0px 0px 0px rgba(0, 0, 0, 0.2)',
        blur: '0 0 20px 0 rgba(0, 0, 0, 0.3)',
        xs: '0px 1px 2px rgba(16, 24, 40, 0.05)',
      },
      screens: {
        max: '1920px',
      },
      transitionTimingFunction: {
        'ease-in-out-custom': 'cubic-bezier(0.45, 0, 0.4, 1)',
        'ease-in-custom': 'cubic-bezier(0.5, 0, 1, 1)',
        'ease-out-custom': 'cubic-bezier(0, 0, 0.4, 1)',
        'linear-custom': 'cubic-bezier(0, 0, 1, 1)',
      },
    },
  },
  corePlugins: {
    preflight: true,
  },
  plugins: [],
};
